### ISSUE TITLE
Unable to go from 0-1 to 1-1

### ISSUE THREAD

**Issue by karthanistyr** [Stanko/dual-range-input#3]
Hi,

on your demo component showcased at https://muffinman.io/blog/native-dual-range-input/

if I set it to 0-1, I am unable to drag the left knob towards the right to set 1-1.

Similar symmetric behaviour to go from 99-100 to 99-99.

On safari on ios18.1.1

maybe a fun edge case to chase down?

cheers

**Comment by Stanko** [comment]
Fixed in v0.9.9
https://github.com/Stanko/dual-range-input/commit/4040fdfa90359e27c35d5da9f1760e7cbe864574
