### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by klotzambein** [Stanko/dual-range-input#5]
Hey, this is a great project and I would love to use it. Could you add a license file? For my use case, MIT would be best, but any open source license should do. 

For more information, I found this article very helpfull: [Licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository).

**Comment by Stanko** [comment]
Ah, I completely forgot to add a license. Thanks for reminding me, I’ll add the MIT license later today when I get to my laptop.

**Comment by Stanko** [comment]
Done https://github.com/Stanko/dual-range-input/commit/c13a4ae79b1fd26465b6608dbb0a48fd8cc2ef68
